[tools]

# `cmake` is used to read `CMakeLists.txt` files,
# and generate build instructions for a specified build generator.
# The build generator used in this project is `ninja`.

# In addition to this, `cmake` is also responsible for creating 
# a `compile_commands.json` file. This file helps language servers 
# like `clangd` to understand the structure of your C project,
# and see which external dependencies you've added to the project,
# so that you get better language support and autocompletion.

# Once the build instructions have been generated,
# `cmake` can then trigger the build generator `ninja`.

# `ninja` will then use the C compiler specified to build the project and
# create a binary executable.
# The C compiler used in this project is `clang`
cmake = "latest"

# The build generator
ninja = "latest"

# The C compiler that will be used by build generator to build the project
# and create an executable binary.
clang = "latest"

# A Code formatter
clang-format = "latest"

# Language support for C files
# The `github:` prefix is used to download a pre-compiled binary from GitHub.
"github:clangd/clangd" = "latest"

# Language support for CMake files
# The `pipx:` prefix is used to download the Python package from PyPI.
# Despite the prefix `pipx`, it is actually using uv to download the tool.
"pipx:cmake-language-server" = { 
    version = "latest", 
    # cmake-language-server is not compatible with pygls version 2,
    # so this is required for it work.
    uvx_args = "--with pygls<2" 
}

# Displays the project structure as a tree diagram
eza = "latest"

#______________________________________________________________________________

[env]

PROJECT_NAME = "c-project"
BUILD_GENERATOR = "Ninja"
C_COMPILER = "clang"

# Use this site to see a list of valid C standards
# https://www.c-language.org/
C_STANDARD = "23"

BUILD_DIR = "build"
BINARY_NAME = "c-project"

# This is the command that will generate the build instructions
# To check if this works, run this:
# bash -c "$CMAKE_GBI_CMD"
CMAKE_GBI_CMD = """
cmake \
    -G {{env.BUILD_GENERATOR}} \
    -DCMAKE_C_COMPILER={{env.C_COMPILER}} \
    -B {{env.BUILD_DIR}}
"""

# This is the command that will build the project and create 
# a binary executable.
# To check if this works, run this:
# bash -c "$CMAKE_GBI_CMD" && bash -c "$CMAKE_BUILD_CMD"
CMAKE_BUILD_CMD = """
cmake --build {{env.BUILD_DIR}}
"""

# This is the command that will run the binary
# To check if this work, run this:
# bash -c "$RUN_BINARY_CMD"
RUN_BINARY_CMD = "./{{env.BUILD_DIR}}/{{env.BINARY_NAME}}"
#______________________________________________________________________________

[shell_alias]
build = "mise build"
clean = "mise clean"
run = "mise runbin"
structure = "mise structure"
#______________________________________________________________________________
